site_name: Kit4DL
site_description: Kit4DL - A quick way to start with machine and deep learning
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: deep purple
    accent: teal
  features:
  - search.suggest
  - search.highlight
  - content.tooltips
  - content.code.annotate
  - content.code.copy
  - content.code.select
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/logo.svg
  favicon: static/logo.svg
  language: en
repo_name: opengeokube/kit4dl
repo_url: https://github.com/opengeokube/kit4dl
edit_uri: ''
use_directory_urls: false
nav:
- About: index.md
- Installation: installation.md
- Quick start: quick.md
- CLI: cli.md
- Neural networks: nn.md
- Data module: datamodule.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_(?!defer_build_mode)"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
        import:
          - https://docs.python.org/3/objects.inv
markdown_extensions:
- admonition
- tables
- toc:
    permalink: true
    title: Page contents
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true